
Deprecate.skip = true if defined?(Deprecate.skip)
Gem::Deprecate.skip = true if defined?(Gem::Deprecate.skip)

source "https://rubygems.org"

gem 'activesupport'
gem 'rspec', '~> 3.1.0'
gem 'sqlite3'
